### ISSUE TITLE
TOC Intersection Observer 영역 관련 이슈

### ISSUE THREAD

**Issue by gyungjae-ham** [junghyeonsu/hyeonsu-jung#36]
안녕하세요 벨로그에서 포트폴리오 글 읽고 동기부여 많이 받았습니다!!
다름이 아니라 포트폴리오를 구경하던 중 왼쪽 사이드바에서 번역 부분은 의도하신건지 클릭 동작은 동작하는데
색상은 변경이 안되는걸 발견해서 이슈 만들어 봅니다 의도하신바라면 바로 삭제하겠습니다!!!

![image](https://user-images.githubusercontent.com/75306311/159597355-b259739b-f70c-4c71-b81f-dadead8fb515.png)

**Comment by junghyeonsu** [comment]
안녕하세요 @hiyee-gj !
우선 이슈 남겨주셔서 정말 감사합니다.

우선 이슈에 대해서 말씀드리면 저 이슈는 예상된 이슈였습니다.
table of contents를 [intersection observer](https://developer.mozilla.org/ko/docs/Web/API/Intersection_Observer_API)를 이용해서 구현했습니다. intersection observer로 옵저버를 만들어서 계속 현재 위치가 어디인지 파악하도록 했습니다. 
현재 옵저버가 위치하는 영역에 있는 컨텐츠를 알려주는거죠.

그런데 옵저버의 영역이 아래 스크린샷과 같이 설정이 되어있습니다.

![스크린샷 2022-03-23 오전 11 10 12 1](https://user-images.githubusercontent.com/54893898/159609789-f5a97c99-4607-409e-9ee7-8deee33f356e.png)

그래서 스크롤을 끝까지 내려도 `React Docs`, `Kubernetes Docs`는 옵저버가 발견하지 못하는거죠.
이 부분에 대해서 제가 고치려고 했는데, 아직 시간이 나지 않아서 고치질 못했네요.
이슈는 그대로 남겨주세요! 제가 한번 고치도록 하겠습니다.

이슈 남겨주셔서 다시 한번 감사합니다~
